import { buildNoteHash, verifyNoteHash, secureCompareHex } from "../src/privacy";

describe("verifyNoteHash", () => {
  const NOTE = "March bonus for contractor #7";
  let expectedHash: string;

  beforeAll(async () => {
    const ref = await buildNoteHash({ note: NOTE });
    expectedHash = ref.noteHash;
  });

  describe("success path", () => {
    it("verifies note text against a hash generated by buildNoteHash", async () => {
      const result = await verifyNoteHash({ note: NOTE, noteHash: expectedHash });
      expect(result.verified).toBe(true);
      expect(result).not.toHaveProperty("failure");
    });

    it("verifies round-trip through attachNoteHash-style payloads", async () => {
      const ref = await buildNoteHash({ note: "invoice 42 late fee" });
      const result = await verifyNoteHash({
        note: "invoice 42 late fee",
        noteHash: ref.noteHash,
      });
      expect(result.verified).toBe(true);
    });

    it("verifies unicode note text", async () => {
      const note = "奥さんの給料 ✓ émoji 🎉";
      const ref = await buildNoteHash({ note });
      const result = await verifyNoteHash({ note, noteHash: ref.noteHash });
      expect(result.verified).toBe(true);
    });

    it("does not include raw note text in the result", async () => {
      const result = await verifyNoteHash({ note: NOTE, noteHash: expectedHash });
      expect(JSON.stringify(result)).not.toContain(NOTE);
    });
  });

  describe("failure paths", () => {
    it("returns NOTE_HASH_MISMATCH when the note does not match", async () => {
      const result = await verifyNoteHash({ note: "different note", noteHash: expectedHash });
      expect(result.verified).toBe(false);
      expect(result.failure?.code).toBe("NOTE_HASH_MISMATCH");
      expect(result.failure?.message).not.toContain("different note");
    });

    it("returns MISSING_NOTE_AND_HASH when note is missing", async () => {
      const result = await verifyNoteHash({ noteHash: expectedHash });
      expect(result.verified).toBe(false);
      expect(result.failure?.code).toBe("MISSING_NOTE_AND_HASH");
    });

    it("returns MISSING_NOTE_AND_HASH when noteHash is missing", async () => {
      const result = await verifyNoteHash({ note: NOTE });
      expect(result.verified).toBe(false);
      expect(result.failure?.code).toBe("MISSING_NOTE_AND_HASH");
    });

    it("returns MISSING_NOTE_AND_HASH when both are missing", async () => {
      const result = await verifyNoteHash({});
      expect(result.verified).toBe(false);
      expect(result.failure?.code).toBe("MISSING_NOTE_AND_HASH");
    });

    it("returns MISSING_NOTE_AND_HASH for non-string note or hash", async () => {
      const badNote = await verifyNoteHash({
        note: 123 as unknown as string,
        noteHash: expectedHash,
      });
      expect(badNote.failure?.code).toBe("MISSING_NOTE_AND_HASH");

      const badHash = await verifyNoteHash({
        note: NOTE,
        noteHash: null as unknown as string,
      });
      expect(badHash.failure?.code).toBe("MISSING_NOTE_AND_HASH");
    });

    it("returns INVALID_EXPECTED_NOTE_HASH for a malformed hash", async () => {
      for (const bad of ["not-a-hash", expectedHash.toUpperCase(), expectedHash.slice(0, 63)]) {
        const result = await verifyNoteHash({ note: NOTE, noteHash: bad });
        expect(result.verified).toBe(false);
        expect(result.failure?.code).toBe("INVALID_EXPECTED_NOTE_HASH");
      }
    });

    it("never throws and never echoes raw note text in failures", async () => {
      const result = await verifyNoteHash({ note: "secret payroll note", noteHash: "zz" });
      expect(result.verified).toBe(false);
      expect(JSON.stringify(result)).not.toContain("secret payroll note");
    });
  });

  describe("edge cases", () => {
    it("verifies empty note text against its own digest", async () => {
      // sha256 of the empty string is a well-defined digest; verification is
      // honest even though buildNoteHash refuses to generate one from "".
      const EMPTY_SHA256 = "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855";
      const result = await verifyNoteHash({ note: "", noteHash: EMPTY_SHA256 });
      expect(result.verified).toBe(true);
    });

    it("rejects a mismatched single-character difference", async () => {
      const a = await verifyNoteHash({ note: "note A", noteHash: expectedHash });
      const b = await verifyNoteHash({ note: "note B", noteHash: expectedHash });
      expect(a.verified).toBe(false);
      expect(b.verified).toBe(false);
    });
  });
});

describe("secureCompareHex", () => {
  const DIGEST_A = "a".repeat(64);
  const DIGEST_B = "b".repeat(64);

  it("returns true for identical digests", () => {
    expect(secureCompareHex(DIGEST_A, DIGEST_A)).toBe(true);
  });

  it("returns false when a character differs anywhere", () => {
    expect(secureCompareHex(DIGEST_A, DIGEST_A.replace("a", "c"))).toBe(false);
  });

  it("returns false for different lengths without throwing", () => {
    expect(secureCompareHex(DIGEST_A.slice(0, 32), DIGEST_A.slice(0, 32))).toBe(true);
    expect(secureCompareHex(DIGEST_A, DIGEST_B.slice(0, 32))).toBe(false);
  });

  it("returns false for fully different digests", () => {
    expect(secureCompareHex(DIGEST_A, DIGEST_B)).toBe(false);
  });
});
