/**
 * Payout Schedule Collision Detection Module
 *
 * Validates scheduled payout disbursements across employees, recipients, and asset streams.
 * Prevents double-disbursement risks, concurrent execution collisions, and minimum
 * interval violations across payroll batches.
 *
 * ## Privacy & Security Guarantees
 * - Recipient addresses, public keys, and identifiers are masked by default in user-facing messages.
 * - Payout amounts are redacted by default in logs and notifications.
 * - Stable, actionable violation codes and suggested fixes.
 */

import { ZkPayrollError, type ErrorContext } from "../core/errors";

/**
 * Standard violation codes for payout schedule collision detection.
 */
export type PayoutScheduleCollisionViolationCode =
  | "EXACT_TIMESTAMP_COLLISION"
  | "MIN_INTERVAL_COLLISION"
  | "DUPLICATE_SCHEDULE_ID"
  | "PERIOD_DISBURSEMENT_COLLISION"
  | "INVALID_RECIPIENT"
  | "INVALID_TIMESTAMP"
  | "INVALID_AMOUNT"
  | "INVALID_SCHEDULE_ID";

/**
 * Input definition for a scheduled payout entry.
 */
export interface PayoutScheduleEntry {
  /** Unique schedule or payout identifier (e.g. "sched-001") */
  scheduleId: string;
  /** Recipient public address or employee identifier */
  recipient: string;
  /** Asset symbol or contract address (e.g. "USDC", "native") */
  asset: string;
  /** Scheduled execution timestamp (epoch ms, ISO date string, or Date) */
  executionTimestamp: number | string | Date;
  /** Optional payout amount (base units) */
  amount?: bigint | number | string;
  /** Optional cutoff deadline timestamp */
  cutoffTimestamp?: number | string | Date;
  /** Optional batch or run identifier (e.g. "batch-101") */
  batchId?: string;
  /** Optional payroll period identifier (e.g. "2026-09") */
  periodId?: string;
  /** Optional frequency or cadence */
  frequency?: string;
  /** Optional status (e.g. "scheduled", "executed", "cancelled") */
  status?: string;
  /** Optional arbitrary metadata */
  metadata?: Record<string, unknown>;
}

/**
 * Fully normalized, canonical payout schedule entry.
 */
export interface NormalizedPayoutSchedule {
  scheduleId: string;
  recipient: string;
  asset: string;
  executionTimestampMs: number;
  executionDateIso: string;
  amount?: bigint;
  cutoffTimestampMs?: number;
  batchId?: string;
  periodId?: string;
  frequency?: string;
  status?: string;
  raw: PayoutScheduleEntry;
}

/**
 * Structured violation descriptor detailing a payout collision issue.
 */
export interface PayoutScheduleCollisionViolation {
  code: PayoutScheduleCollisionViolationCode;
  scheduleId: string;
  redactedScheduleId: string;
  conflictingScheduleId?: string;
  redactedConflictingScheduleId?: string;
  recipient: string;
  redactedRecipient: string;
  asset: string;
  executionTimestampMs?: number;
  conflictingTimestampMs?: number;
  timeDeltaMs?: number;
  minIntervalMs?: number;
  batchId?: string;
  periodId?: string;
  message: string;
  redactedMessage: string;
  suggestedFix: string;
}

/**
 * Configuration options for payout schedule collision detection.
 */
export interface PayoutScheduleCollisionOptions {
  /**
   * Minimum required time separation between payouts to the same recipient and asset (ms).
   * Defaults to 0 (only exact same timestamp is flagged as a collision).
   */
  minIntervalMs?: number;
  /**
   * Whether to partition collisions by asset.
   * If true (default), payouts to the same recipient in different assets do not collide.
   * If false, any overlapping payout to the recipient regardless of asset is flagged.
   */
  matchAsset?: boolean;
  /**
   * Whether to enforce a single payout per recipient per periodId.
   * Defaults to false.
   */
  enforceUniquePerPeriod?: boolean;
  /**
   * Statuses to ignore during collision detection (e.g. ['cancelled', 'failed']).
   * Defaults to ['cancelled'].
   */
  ignoreStatuses?: string[];
  /**
   * Mask recipient addresses and identifiers in messages.
   * Defaults to true.
   */
  redactIdentifiers?: boolean;
  /**
   * Mask amounts in messages.
   * Defaults to true.
   */
  redactAmounts?: boolean;
  /**
   * Require amount to be strictly positive if provided.
   * Defaults to true.
   */
  validateAmount?: boolean;
}

/**
 * Report generated by payout schedule collision analysis.
 */
export interface PayoutScheduleCollisionReport {
  isValid: boolean;
  violations: PayoutScheduleCollisionViolation[];
  normalizedSchedules: NormalizedPayoutSchedule[];
  summary: {
    totalEntries: number;
    validCount: number;
    violationCount: number;
    collisionCount: number;
    duplicateIdCount: number;
    invalidEntryCount: number;
    hasCollisions: boolean;
  };
}

/**
 * Typed error thrown when a payout schedule collision is detected.
 */
export class PayoutScheduleCollisionError extends ZkPayrollError {
  public readonly violations: readonly PayoutScheduleCollisionViolation[];
  public readonly suggestedFix: string;

  constructor(
    message: string,
    violations: PayoutScheduleCollisionViolation[] = [],
    context: ErrorContext = {}
  ) {
    super(message, "PAYOUT_SCHEDULE_COLLISION", context);
    this.name = "PayoutScheduleCollisionError";
    this.violations = Object.freeze([...violations]);
    this.suggestedFix =
      violations[0]?.suggestedFix ??
      "Reschedule conflicting payouts to distinct execution times or spacing intervals.";
    Object.setPrototypeOf(this, PayoutScheduleCollisionError.prototype);
  }
}

/**
 * Safely redact a recipient address or public key for audit logs and UI.
 */
export function redactRecipientAddress(address?: string): string {
  if (!address || typeof address !== "string") {
    return "[ANONYMOUS_RECIPIENT]";
  }
  const clean = address.trim();
  if (clean.length === 0) {
    return "[ANONYMOUS_RECIPIENT]";
  }
  if (clean.length <= 6) {
    return "[REDACTED_RECIPIENT]";
  }
  return `${clean.slice(0, 3)}***${clean.slice(-3)}`;
}

/**
 * Safely redact a schedule identifier.
 */
export function redactScheduleId(id?: string): string {
  if (!id || typeof id !== "string") {
    return "[ANONYMOUS_SCHEDULE]";
  }
  const clean = id.trim();
  if (clean.length === 0) {
    return "[ANONYMOUS_SCHEDULE]";
  }
  if (clean.length <= 4) {
    return "[SCHEDULE_REDACTED]";
  }
  return `${clean.slice(0, 3)}***${clean.slice(-3)}`;
}

/**
 * Parses timestamp value into Unix epoch milliseconds.
 */
export function parseScheduleTimestamp(val: unknown): number | null {
  if (val === undefined || val === null) {
    return null;
  }
  if (typeof val === "number") {
    return isNaN(val) || !isFinite(val) ? null : val;
  }
  if (val instanceof Date) {
    const time = val.getTime();
    return isNaN(time) ? null : time;
  }
  if (typeof val === "string") {
    const trimmed = val.trim();
    if (!trimmed) return null;
    const parsed = Date.parse(trimmed);
    if (!isNaN(parsed)) return parsed;
    const num = Number(trimmed);
    if (!isNaN(num) && isFinite(num)) return num;
  }
  return null;
}

/**
 * Parses amount into bigint.
 */
function parsePayoutAmount(val: unknown): bigint | null {
  if (val === undefined || val === null) return null;
  if (typeof val === "bigint") return val;
  if (typeof val === "number") {
    if (isNaN(val) || !isFinite(val) || !Number.isInteger(val)) return null;
    return BigInt(val);
  }
  if (typeof val === "string") {
    const trimmed = val.trim();
    if (/^-?\d+$/.test(trimmed)) {
      try {
        return BigInt(trimmed);
      } catch {
        return null;
      }
    }
  }
  return null;
}

/**
 * Normalizes and validates a single payout schedule entry.
 */
export function normalizePayoutScheduleEntry(
  input: PayoutScheduleEntry,
  options: PayoutScheduleCollisionOptions = {}
): {
  schedule?: NormalizedPayoutSchedule;
  violation?: PayoutScheduleCollisionViolation;
} {
  const redact = options.redactIdentifiers !== false;
  const rawId = input?.scheduleId;
  const scheduleId = typeof rawId === "string" ? rawId.trim() : "";
  const displayId = redact ? redactScheduleId(scheduleId) : scheduleId || "[UNKNOWN]";

  // 1. Validate schedule ID
  if (!scheduleId) {
    return {
      violation: {
        code: "INVALID_SCHEDULE_ID",
        scheduleId: "",
        redactedScheduleId: "[ANONYMOUS_SCHEDULE]",
        recipient: "",
        redactedRecipient: "[ANONYMOUS_RECIPIENT]",
        asset: input?.asset ?? "",
        message: "Payout schedule identifier is required and must not be empty.",
        redactedMessage: "Schedule identifier is required.",
        suggestedFix:
          "Assign a unique non-empty string identifier (e.g. 'sched-001') to the payout schedule.",
      },
    };
  }

  // 2. Validate recipient
  const rawRecipient = input?.recipient;
  const recipient = typeof rawRecipient === "string" ? rawRecipient.trim() : "";
  const displayRecipient = redact ? redactRecipientAddress(recipient) : recipient;

  if (!recipient) {
    return {
      violation: {
        code: "INVALID_RECIPIENT",
        scheduleId,
        redactedScheduleId: displayId,
        recipient: "",
        redactedRecipient: "[ANONYMOUS_RECIPIENT]",
        asset: input?.asset ?? "",
        message: `Payout schedule '${displayId}' is missing a recipient address or employee identifier.`,
        redactedMessage: "Payout schedule is missing recipient address.",
        suggestedFix: "Provide a valid recipient account address or employee ID.",
      },
    };
  }

  // 3. Validate timestamp
  const executionMs = parseScheduleTimestamp(input.executionTimestamp);
  if (executionMs === null || executionMs < 0) {
    return {
      violation: {
        code: "INVALID_TIMESTAMP",
        scheduleId,
        redactedScheduleId: displayId,
        recipient,
        redactedRecipient: displayRecipient,
        asset: input?.asset ?? "",
        message: `Payout schedule '${displayId}' has an invalid or missing execution timestamp: ${String(input.executionTimestamp)}.`,
        redactedMessage: "Payout schedule has an invalid execution timestamp.",
        suggestedFix:
          "Provide a valid epoch millisecond timestamp, ISO date string, or Date object for executionTimestamp.",
      },
    };
  }

  // 4. Validate amount if present
  let amount: bigint | undefined = undefined;
  if (input.amount !== undefined && input.amount !== null) {
    const parsedAmount = parsePayoutAmount(input.amount);
    if (parsedAmount === null) {
      return {
        violation: {
          code: "INVALID_AMOUNT",
          scheduleId,
          redactedScheduleId: displayId,
          recipient,
          redactedRecipient: displayRecipient,
          asset: input?.asset ?? "",
          message: `Payout schedule '${displayId}' has an invalid amount representation: ${String(input.amount)}.`,
          redactedMessage: "Payout schedule has an invalid amount.",
          suggestedFix:
            "Specify payout amount as a non-negative integer or bigint base unit value.",
        },
      };
    }

    if (options.validateAmount !== false && parsedAmount <= 0n) {
      return {
        violation: {
          code: "INVALID_AMOUNT",
          scheduleId,
          redactedScheduleId: displayId,
          recipient,
          redactedRecipient: displayRecipient,
          asset: input?.asset ?? "",
          message: `Payout schedule '${displayId}' amount must be strictly greater than zero.`,
          redactedMessage: "Payout schedule amount must be greater than zero.",
          suggestedFix: "Ensure the payout amount is a positive number.",
        },
      };
    }
    amount = parsedAmount;
  }

  const asset = (input.asset || "native").trim();
  const cutoffTimestampMs = parseScheduleTimestamp(input.cutoffTimestamp) ?? undefined;

  return {
    schedule: {
      scheduleId,
      recipient,
      asset,
      executionTimestampMs: executionMs,
      executionDateIso: new Date(executionMs).toISOString(),
      amount,
      cutoffTimestampMs,
      batchId: input.batchId?.trim() || undefined,
      periodId: input.periodId?.trim() || undefined,
      frequency: input.frequency?.trim() || undefined,
      status: input.status?.trim().toLowerCase() || undefined,
      raw: input,
    },
  };
}

/**
 * Checks whether two payout schedules collide according to configuration.
 */
export function isPayoutScheduleColliding(
  a: PayoutScheduleEntry | NormalizedPayoutSchedule,
  b: PayoutScheduleEntry | NormalizedPayoutSchedule,
  options: PayoutScheduleCollisionOptions = {}
): boolean {
  const normA = "executionTimestampMs" in a ? a : normalizePayoutScheduleEntry(a, options).schedule;
  const normB = "executionTimestampMs" in b ? b : normalizePayoutScheduleEntry(b, options).schedule;

  if (!normA || !normB) return false;

  // Recipient check
  if (normA.recipient !== normB.recipient) return false;

  // Asset check
  if (options.matchAsset !== false && normA.asset.toUpperCase() !== normB.asset.toUpperCase()) {
    return false;
  }

  // Ignored statuses
  const ignoreStatuses = (options.ignoreStatuses ?? ["cancelled"]).map((s) => s.toLowerCase());
  if (normA.status && ignoreStatuses.includes(normA.status)) return false;
  if (normB.status && ignoreStatuses.includes(normB.status)) return false;

  // Enforce unique per period if configured
  if (options.enforceUniquePerPeriod && normA.periodId && normB.periodId) {
    if (normA.periodId === normB.periodId) return true;
  }

  // Exact timestamp or within minIntervalMs
  const minInterval = options.minIntervalMs ?? 0;
  const timeDelta = Math.abs(normA.executionTimestampMs - normB.executionTimestampMs);

  return minInterval === 0
    ? normA.executionTimestampMs === normB.executionTimestampMs
    : timeDelta < minInterval;
}

/**
 * Detects all collisions and validation errors across a list of payout schedule entries.
 */
export function detectPayoutScheduleCollisions(
  schedules: PayoutScheduleEntry[] = [],
  options: PayoutScheduleCollisionOptions = {}
): PayoutScheduleCollisionReport {
  const violations: PayoutScheduleCollisionViolation[] = [];
  const normalizedSchedules: NormalizedPayoutSchedule[] = [];
  const redact = options.redactIdentifiers !== false;
  const ignoreStatuses = (options.ignoreStatuses ?? ["cancelled"]).map((s) => s.toLowerCase());
  const minInterval = options.minIntervalMs ?? 0;
  const matchAsset = options.matchAsset !== false;
  const enforceUniquePerPeriod = options.enforceUniquePerPeriod === true;

  let duplicateIdCount = 0;
  let invalidEntryCount = 0;
  let collisionCount = 0;

  const seenIds = new Map<string, number>();

  // 1. Normalize individual entries and detect ID collisions
  for (let i = 0; i < schedules.length; i++) {
    const raw = schedules[i];
    const { schedule, violation } = normalizePayoutScheduleEntry(raw, options);

    if (violation) {
      violations.push(violation);
      invalidEntryCount++;
      continue;
    }

    if (!schedule) continue;

    // Check duplicate scheduleId
    if (seenIds.has(schedule.scheduleId)) {
      duplicateIdCount++;
      const firstIndex = seenIds.get(schedule.scheduleId)!;
      const displayId = redact ? redactScheduleId(schedule.scheduleId) : schedule.scheduleId;
      const displayRecipient = redact
        ? redactRecipientAddress(schedule.recipient)
        : schedule.recipient;

      violations.push({
        code: "DUPLICATE_SCHEDULE_ID",
        scheduleId: schedule.scheduleId,
        redactedScheduleId: displayId,
        conflictingScheduleId: schedules[firstIndex].scheduleId,
        redactedConflictingScheduleId: redact
          ? redactScheduleId(schedules[firstIndex].scheduleId)
          : schedules[firstIndex].scheduleId,
        recipient: schedule.recipient,
        redactedRecipient: displayRecipient,
        asset: schedule.asset,
        message: `Duplicate payout schedule identifier detected: '${displayId}'.`,
        redactedMessage: "Duplicate schedule identifier detected in payout calendar.",
        suggestedFix: "Ensure all payout schedules have unique scheduleId values.",
      });
    } else {
      seenIds.set(schedule.scheduleId, i);
    }

    normalizedSchedules.push(schedule);
  }

  // 2. Pairwise collision check across active normalized schedules
  const activeSchedules = normalizedSchedules.filter(
    (s) => !s.status || !ignoreStatuses.includes(s.status)
  );

  for (let i = 0; i < activeSchedules.length; i++) {
    for (let j = i + 1; j < activeSchedules.length; j++) {
      const a = activeSchedules[i];
      const b = activeSchedules[j];

      // Same recipient?
      if (a.recipient !== b.recipient) continue;

      // Same asset?
      if (matchAsset && a.asset.toUpperCase() !== b.asset.toUpperCase()) continue;

      const displayA = redact ? redactScheduleId(a.scheduleId) : a.scheduleId;
      const displayB = redact ? redactScheduleId(b.scheduleId) : b.scheduleId;
      const displayRecipient = redact ? redactRecipientAddress(a.recipient) : a.recipient;
      const timeDelta = Math.abs(a.executionTimestampMs - b.executionTimestampMs);

      // Check period-based collision
      if (enforceUniquePerPeriod && a.periodId && b.periodId && a.periodId === b.periodId) {
        collisionCount++;
        violations.push({
          code: "PERIOD_DISBURSEMENT_COLLISION",
          scheduleId: a.scheduleId,
          redactedScheduleId: displayA,
          conflictingScheduleId: b.scheduleId,
          redactedConflictingScheduleId: displayB,
          recipient: a.recipient,
          redactedRecipient: displayRecipient,
          asset: a.asset,
          executionTimestampMs: a.executionTimestampMs,
          conflictingTimestampMs: b.executionTimestampMs,
          timeDeltaMs: timeDelta,
          periodId: a.periodId,
          batchId: a.batchId,
          message: `Payout collision: Recipient ${displayRecipient} has multiple payouts scheduled for period '${a.periodId}' across schedules '${displayA}' and '${displayB}'.`,
          redactedMessage: `Multiple payouts scheduled for recipient in period '${a.periodId}'.`,
          suggestedFix: "Consolidate payouts into a single schedule entry or remove the duplicate.",
        });
        continue;
      }

      // Check timestamp collision
      const isExactCollision = a.executionTimestampMs === b.executionTimestampMs;
      const isIntervalCollision = minInterval > 0 && timeDelta < minInterval;

      if (isExactCollision) {
        collisionCount++;
        const dateIso = a.executionDateIso;
        violations.push({
          code: "EXACT_TIMESTAMP_COLLISION",
          scheduleId: a.scheduleId,
          redactedScheduleId: displayA,
          conflictingScheduleId: b.scheduleId,
          redactedConflictingScheduleId: displayB,
          recipient: a.recipient,
          redactedRecipient: displayRecipient,
          asset: a.asset,
          executionTimestampMs: a.executionTimestampMs,
          conflictingTimestampMs: b.executionTimestampMs,
          timeDeltaMs: 0,
          batchId: a.batchId,
          message: `Exact payout collision: Recipient ${displayRecipient} has multiple payouts scheduled at ${dateIso} for asset ${a.asset} ('${displayA}' and '${displayB}').`,
          redactedMessage: `Exact payout timestamp collision detected for recipient and asset ${a.asset}.`,
          suggestedFix:
            "Merge the payouts or adjust the execution timestamp of one of the schedules.",
        });
      } else if (isIntervalCollision) {
        collisionCount++;
        violations.push({
          code: "MIN_INTERVAL_COLLISION",
          scheduleId: a.scheduleId,
          redactedScheduleId: displayA,
          conflictingScheduleId: b.scheduleId,
          redactedConflictingScheduleId: displayB,
          recipient: a.recipient,
          redactedRecipient: displayRecipient,
          asset: a.asset,
          executionTimestampMs: a.executionTimestampMs,
          conflictingTimestampMs: b.executionTimestampMs,
          timeDeltaMs: timeDelta,
          minIntervalMs: minInterval,
          batchId: a.batchId,
          message: `Payout interval collision: Schedules '${displayA}' and '${displayB}' for recipient ${displayRecipient} are separated by ${timeDelta}ms (minimum required: ${minInterval}ms).`,
          redactedMessage: `Payout schedules for recipient are scheduled closer than minimum interval.`,
          suggestedFix: `Space execution times by at least ${minInterval}ms to satisfy payout interval separation.`,
        });
      }
    }
  }

  const validCount = Math.max(0, schedules.length - violations.length);

  return {
    isValid: violations.length === 0,
    violations,
    normalizedSchedules,
    summary: {
      totalEntries: schedules.length,
      validCount,
      violationCount: violations.length,
      collisionCount,
      duplicateIdCount,
      invalidEntryCount,
      hasCollisions: collisionCount > 0,
    },
  };
}

/**
 * Asserts that a list of payout schedule entries has zero collisions.
 * Throws a typed `PayoutScheduleCollisionError` if collisions are found.
 */
export function assertNoPayoutScheduleCollision(
  schedules: PayoutScheduleEntry[] = [],
  options: PayoutScheduleCollisionOptions = {}
): void {
  const report = detectPayoutScheduleCollisions(schedules, options);
  if (!report.isValid) {
    const firstViolation = report.violations[0];
    const message = `Payout schedule validation failed with ${report.violations.length} violation(s). First violation: ${firstViolation.message}`;
    throw new PayoutScheduleCollisionError(message, report.violations, {
      violationCount: report.violations.length,
      firstViolationCode: firstViolation.code,
      scheduleId: firstViolation.scheduleId,
      conflictingScheduleId: firstViolation.conflictingScheduleId,
    });
  }
}

/**
 * Finds all existing schedules that collide with a candidate schedule entry.
 */
export function findPayoutScheduleCollisions(
  candidate: PayoutScheduleEntry,
  existingSchedules: PayoutScheduleEntry[] = [],
  options: PayoutScheduleCollisionOptions = {}
): PayoutScheduleCollisionViolation[] {
  const { schedule: normCandidate, violation: candidateViolation } = normalizePayoutScheduleEntry(
    candidate,
    options
  );
  if (candidateViolation) {
    return [candidateViolation];
  }
  if (!normCandidate) return [];

  const report = detectPayoutScheduleCollisions([...existingSchedules, candidate], options);
  return report.violations.filter(
    (v) => v.scheduleId === candidate.scheduleId || v.conflictingScheduleId === candidate.scheduleId
  );
}

/**
 * Filters a list of payout schedule entries into valid and colliding entries.
 */
export function filterNonCollidingPayoutSchedules(
  schedules: PayoutScheduleEntry[] = [],
  options: PayoutScheduleCollisionOptions = {}
): {
  validSchedules: PayoutScheduleEntry[];
  collidingSchedules: PayoutScheduleEntry[];
  report: PayoutScheduleCollisionReport;
} {
  const report = detectPayoutScheduleCollisions(schedules, options);
  if (report.isValid) {
    return {
      validSchedules: [...schedules],
      collidingSchedules: [],
      report,
    };
  }

  const collidingIds = new Set<string>();
  for (const v of report.violations) {
    if (v.scheduleId) collidingIds.add(v.scheduleId);
    if (v.conflictingScheduleId) collidingIds.add(v.conflictingScheduleId);
  }

  const validSchedules = schedules.filter((s) => !collidingIds.has(s.scheduleId));
  const collidingSchedules = schedules.filter((s) => collidingIds.has(s.scheduleId));

  return {
    validSchedules,
    collidingSchedules,
    report,
  };
}
